mindmap
  root((Main Topic))
    Theme 1
      Sub-topic A
        Detail 1
        Detail 2
      Sub-topic B
    Theme 2
      Sub-topic C
      Sub-topic D
        Detail 3
    Theme 3
      Sub-topic E
      Sub-topic F
